# Generated by Django 3.2 on 2021-04-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_jop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='descirption',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
